##' A function to return the figi to decaf ctype file mappers.
##'
##' This is the description
##'
##' @return Returns a list with the mapping.
##' @export
ctype_mapping_figi_to_decaf <- function() {

    list("id"=NA,
         "EURO-DOLLAR"=NA,
         "created_at"=NA,
         "updated_at"=NA,
         "figitypeccy"=list("GLOBAL"="USD",
                            "EURO MTN"="EUR",
                            "EURO-ZONE"="EUR",
                            "EURO-DOLLAR"="USD",
                            "EURO NON-DOLLAR"="EUR"),
         "figictypes"=list("ADR"=list("ctype"="SHRE",
                                      "stype"="ADR"),
                           "CDI"=list("ctype"="SHRE",
                                      "stype"="Depositary Receipt"),
                           "ETP"=list("ctype"="SHRE",
                                      "stype"="ETP"),
                           "MLP"=list("ctype"="SHRE",
                                      "stype"="Partnership"),
                           "NVDR"=list("ctype"="SHRE",
                                       "stype"="NVDR"),
                           "REIT"=list("ctype"="SHRE",
                                       "stype"="REIT"),
                           "Unit"=list("ctype"="SHRE",
                                       "stype"="Unit"),
                           "Right"=list("ctype"="SHRE",
                                        "stype"="Right"),
                           "GLOBAL"=list("ctype"="BOND",
                                         "stype"="GLOBAL"),
                           "Yankee"=list("ctype"="BOND",
                                         "stype"=""),
                           "DOMESTIC"=list("ctype"="BOND",
                                           "stype"="DOMESTIC"),
                           "EURO MTN"=list("ctype"="BOND",
                                           "stype"="EURO MTN"),
                           "Ltd Part"=list("ctype"="SHRE",
                                           "stype"="Partnership"),
                           "EURO-ZONE"=list("ctype"="BOND",
                                            "stype"="EURO-ZONE"),
                           "Index WRT"=list("ctype"="SHRE",
                                            "stype"="Index WRT"),
                           "Dutch Cert"=list("ctype"="SHRE",
                                             "stype"="Dutch Cert"),
                           "Equity WRT"=list("ctype"="SHRE",
                                             "stype"="Equity WRT"),
                           "Preference"=list("ctype"="SHRE",
                                             "stype"="Preference"),
                           "EURO-DOLLAR"=list("ctype"="BOND",
                                              "stype"="EURO-DOLLAR"),
                           "Foreign Sh."=list("ctype"="SHRE",
                                              "stype"="Common Stock"),
                           "NY Reg Shrs"=list("ctype"="SHRE",
                                              "stype"="Depositary Receipt"),
                           "US Domestic"=list("ctype"="BOND",
                                              "stype"=""),
                           "Common Stock"=list("ctype"="SHRE",
                                               "stype"="Common Stock"),
                           "DOMESTIC MTN"=list("ctype"="BOND",
                                               "stype"="DOMESTIC MTN"),
                           "Equity Index"=list("ctype"="SHRE",
                                               "stype"="Equity Index"),
                           "Index Option"=list("ctype"="OPT",
                                               "stype"="Index Option"),
                           "Tracking Stk"=list("ctype"="SHRE",
                                               "stype"="Common Stock"),
                           "Equity Option"=list("ctype"="OPT",
                                                "stype"="Equity Option"),
                           "Fund of Funds"=list("ctype"="SHRE",
                                                "stype"="Fund of Funds"),
                           "Open-End Fund"=list("ctype"="SHRE",
                                                "stype"="Open-End Fund"),
                           "US Government"=list("ctype"="BOND",
                                                "stype"=""),
                           "PRIV PLACEMENT"=list("ctype"="BOND",
                                                 "stype"="Private Placement"),
                           "Closed-End Fund"=list("ctype"="SHRE",
                                                  "stype"="Closed-End Fund"),
                           "EURO NON-DOLLAR"=list("ctype"="BOND",
                                                  "stype"="EURO NON-DOLLAR"),
                           "Open-End Fund.1"=list("ctype"="SHRE",
                                                  "stype"="Open-End Fund"),
                           "Stapled Security"=list("ctype"="SHRE",
                                                   "stype"="Stapled Security"),
                           "Depositary Receipt"=list("ctype"="SHRE",
                                                     "stype"="Depositary Receipt"),
                           "Physical index future."=list("ctype"="SHRE",
                                                         "stype"="Depositary Receipt"),
                           "Financial index future."=list("ctype"="FUT",
                                                          "stype"="Index Future"),
                           "Physical commodity option."=list("ctype"="FUT",
                                                             "stype"="Index Future"),
                           "Financial commodity future."=list("ctype"="OPT",
                                                              "stype"="Commodity Option"),
                           "Financial commodity option."=list("ctype"="FUT",
                                                              "stype"="Commodity Future")))

}
